CREATE DATABASE IF NOT EXISTS DB_EVENTICKET;

USE DB_EVENTICKET;

CREATE TABLE IF NOT EXISTS `EVENTS`(
`ID` INT(11) AUTO_INCREMENT,
`TITLE` VARCHAR(120) NOT NULL,
`DESCRIPTION` VARCHAR(500) NOT NULL,
`DATE` TIMESTAMP NOT NULL,
`IMAGE`TEXT NOT NULL,

PRIMARY KEY(`ID`)
);

CREATE TABLE IF NOT EXISTS `PRE_REGISTRATION`(
`ID` INT(11) AUTO_INCREMENT,
`ID_EVENT` INT(11) NOT NULL,
`FISRT_NAME` VARCHAR(255) NOT NULL,
`LAST_NAME`VARCHAR(255) NOT NULL,
`BIRTHDATE` DATE NOT NULL,

PRIMARY KEY(`ID`),
FOREIGN KEY(`ID_EVENT`) REFERENCES `EVENTS`(`ID`)
);

INSERT INTO EVENTS(TITLE,DESCRIPTION,`DATE`,IMAGE) VALUES("Sebastian Yatra","No te puedes perder el maravilloso concierto de Sebastián Yatra en CD.México. Disfruta de los mejores momentos del concierto en vivo, no te lo puedes perder.",
'2019-04-10 21:00:00','imagen1.JPG');

